// One-off helper: extracts Lucide icon bodies into wwwroot/js/SFDIcons.js and converts the
// original Tailwind-wrapped stylesheet into plain CSS. Run from the SFD folder.
import fs from 'node:fs';
import path from 'node:path';

const [iconsDir, cssIn] = process.argv.slice(2);
const names = `check lock-keyhole log-out mail radio smartphone chevron-down chevron-right file-up x arrow-up-right circle-help map route shield-check loader-circle crosshair layers maximize-2 minus plus expand arrow-down-up battery navigation-2 users footprints waypoints bell circle-pause wifi-off calendar-days download refresh-cw file-chart-column layout-dashboard chart-no-axes-combined menu settings-2 search sliders-horizontal arrow-right arrow-left locate-fixed navigation pause map-pin`.split(' ');

const icons = {};
for (const name of names) {
  const svg = fs.readFileSync(path.join(iconsDir, name + '.svg'), 'utf8');
  icons[name] = svg.replace(/^[\s\S]*?>\s*(?=<(?:path|circle|line|rect|polyline|polygon|ellipse))/, '').replace(/<\/svg>\s*$/, '').replace(/\s+/g, ' ').trim();
}
fs.mkdirSync('wwwroot/icons', { recursive: true });
for (const [name, body] of Object.entries(icons)) {
  fs.writeFileSync(`wwwroot/icons/${name}.svg`, body + '\n');
}
fs.writeFileSync('wwwroot/js/SFDIcons.js', '// Generated by tools/build-assets.mjs from lucide-static (ISC).\nwindow.SFD_ICONS = ' + JSON.stringify(icons, null, 1) + ';\n');

let css = fs.readFileSync(cssIn, 'utf8');
css = css.replace(/^@import[^\n]*\n/, '').replace(/^@tailwind[^\n]*\n/gm, '');
// unwrap `@layer base { ... }` (first top-level block)
const start = css.indexOf('@layer base {');
let depth = 0, end = -1;
for (let i = css.indexOf('{', start); i < css.length; i++) {
  if (css[i] === '{') depth++;
  else if (css[i] === '}' && --depth === 0) { end = i; break; }
}
css = css.slice(0, start) + css.slice(start + '@layer base {'.length, end) + css.slice(end + 1);
fs.writeFileSync('wwwroot/css/site.css', css);
console.log('icons', Object.keys(icons).length, 'css bytes', css.length);
